<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Salesperson;

class UpdateSalespersonProgress extends Command
{
    protected $signature = 'salespeople:update-progress';
    protected $description = 'Update progress of all salespeople and generate projects when progress reaches 100%';

    public function handle()
    {
        $salespeople = Salesperson::active()->get();

        foreach ($salespeople as $salesperson) {
            try {
                $projectGenerated = $salesperson->updateProgress();
                
                if ($projectGenerated) {
                    $this->info("New project generated by salesperson {$salesperson->name}");
                }
            } catch (\Exception $e) {
                $this->error("Failed to process salesperson {$salesperson->name}: " . $e->getMessage());
            }
        }

        $this->info('Salesperson progress updated successfully.');
    }
}
